// OpenGIS Implementation Specification for Geographic information - Simple feature access
// Section 7.1.3.3 (e)
// https://portal.ogc.org/files/?artifact_id=25354
enum OpenGisGeometryTypes {
  CURVE = "CURVE",
  CURVEM = "CURVEM",
  CURVEZ = "CURVEZ",
  CURVEZM = "CURVEZM",

  // NOTE: PostGIS uses "GeometryCollection"
  GEOMCOLLECTION = "GEOMCOLLECTION",
  GEOMCOLLECTIONM = "GEOMCOLLECTIONM",
  GEOMCOLLECTIONZ = "GEOMCOLLECTIONZ",
  GEOMCOLLECTIONZM = "GEOMCOLLECTIONZM",

  GEOMETRY = "GEOMETRY",
  GEOMETRYZ = "GEOMETRYZ",
  GEOMETRYZM = "GEOMETRYZM",

  LINESTRING = "LINESTRING",
  LINESTRINGM = "LINESTRINGM",
  LINESTRINGZ = "LINESTRINGZ",
  LINESTRINGZM = "LINESTRINGZM",

  MULTILINESTRING = "MULTILINESTRING",
  MULTILINESTRINGM = "MULTILINESTRINGM",
  MULTILINESTRINGZM = "MULTILINESTRINGZM",
  MULTILINESTRINGZ = "MULTILINESTRINGZ",

  MULTIPOINT = "MULTIPOINT",
  MULTIPOINTM = "MULTIPOINTM",
  MULTIPOINTZM = "MULTIPOINTZM",
  MULTIPOINTZ = "MULTIPOINTZ",

  MULTIPOLYGON = "MULTIPOLYGON",
  MULTIPOLYGONM = "MULTIPOLYGONM",
  MultiPolygonZM = "MultiPolygonZM",
  MULTIPOLYGONZ = "MULTIPOLYGONZ",

  POINT = "POINT",
  POINTM = "POINTM",
  POINTZM = "POINTZM",
  POINTZ = "POINTZ",

  POLYGON = "POLYGON",
  POLYGONM = "POLYGONM",
  POLYGONZM = "POLYGONZM",
  POLYGONZ = "POLYGONZ",

  POLYHEDRALSURFACE = "POLYHEDRALSURFACE",
  POLYHEDRALSURFACEM = "POLYHEDRALSURFACEM",
  POLYHEDRALSURFACEZM = "POLYHEDRALSURFACEZM",
  POLYHEDRALSURFACEZ = "POLYHEDRALSURFACEZ",

  SURFACE = "SURFACE",
  SURFACEM = "SURFACEM",
  SURFACEZM = "SURFACEZM",
  SURFACEZ = "SURFACEZ",
}

export default OpenGisGeometryTypes;
