#!/usr/bin/env node

require("ts-node").register();
require("tsconfig-paths").register();

const yargs = require("yargs/yargs");
const { hideBin } = require("yargs/helpers");

const dama_events = require("data_manager/events").default;
const logger = require("data_manager/logger").default;
const { runInDamaContext } = require("data_manager/contexts");

const text_columns = require("./text_columns").default;

const {
  default: etl,
  pg_env_yargs_config,
  file_path_yargs_config,
  logging_level_yargs_config,
} = require("data_utils/gis/etl");

const layer_name = "National_Bridge_Inventory";

const source_info = {
  name: "us_bts_national_bridge_inventory",
  display_name: "U.S. BTS National Bridge Inventory",
};

const view_info = {
  table_schema: "us_bureau_of_transportation_statistics",
  table_name: "national_bridge_inventory",
  source_url:
    "https://geodata.bts.gov/datasets/usdot::national-bridge-inventory",
  publisher: "U.S. Department of Transportation",
};

// function reviseTableDescriptor(table_descriptor) {
// for (const c of text_columns) {
// const column_type = table_descriptor.columnTypes.find(
// ({ col }) => col === c
// );

// console.log("==> column_name:", c);

// column_type.db_type = "TEXT";
// }

// return table_descriptor;
// }

const { pg_env, file_path, logging_level } = yargs(hideBin(process.argv))
  .strict()
  .options({
    file_path: file_path_yargs_config,
    pg_env: pg_env_yargs_config,
    logging_level: logging_level_yargs_config,
  }).argv;

logger.level = logging_level;

const config = {
  file_path,
  layer_name,
  source_info,
  view_info,
  // reviseTableDescriptor,
  preserve_text_fields: true,
};

async function main() {
  const etl_context_id = await dama_events.spawnEtlContext(null, null, pg_env);

  logger.info(`==> etl_context_id: ${etl_context_id}`);

  await runInDamaContext(
    {
      meta: { pgEnv: pg_env, etl_context_id },
    },
    () => etl(config)
  );
}

main();
