#!/usr/bin/env node

require("ts-node").register();
require("tsconfig-paths").register();

const { runETLFromCLI } = require("data_utils/gis/etl");

const layer_name = "tl_2010_36_bg10";

const source_info = {
  name: "us_census_block_group",
  display_name: "US Census Block Group",
  description:
    "Census Block Groups are statistical divisions of census tracts and composed of clusters of census blocks. A census block group consists of all census blocks whose numbers begin with the same digit in a given census tract. Block groups typically contain between 600 and 3,000 people, with an optimum size of 1,500.",
};

const view_info = {
  table_schema: "us_census_tiger",
  table_name: "block_group_2010",
  geography_version: 36,
  source_url:
    "https://www2.census.gov/geo/pvs/tiger2010st/36_New_York/36/tl_2010_36_bg10.zip",
  publisher: "US Census TIGER",
};

runETLFromCLI({
  layer_name,
  source_info,
  view_info,
  preserve_text_fields: true,
});
