#! /bin/bash

# NOTE: Must specify the OSM layer when dumping PBF to GeoJSON.
# https://trac.osgeo.org/gdal/ticket/6474
#
# https://gdal.org/drivers/vector/geojsonseq.html

set -e

ogr2ogr \
  -F GeoJSONSeq \
  /vsistdout/ \
  ../initial_data/new-york-220101.osm.pbf lines \
| ../other_tags_parser \
| ../../../data_utils/streaming/ndjson_to_geojson \
> ny_roadways.osm.geojson
