#!/usr/bin/env node

require("ts-node").register();
require("tsconfig-paths").register();

const { basename } = require("path");

const yargs = require("yargs/yargs");
const { hideBin } = require("yargs/helpers");

const dama_events = require("data_manager/events").default;
const logger = require("data_manager/logger").default;
const { runInDamaContext } = require("data_manager/contexts");

const {
  default: etl,
  pg_env_yargs_config,
  logging_level_yargs_config,
  file_path_yargs_config,
} = require("data_utils/gis/etl");

const source_info = {
  name: "osm_roadways",
  display_name: "OSM Roadways",
};

const view_info = {
  table_schema: "osm",
  table_name: "roadways",
  geography_version: 36,
  publisher: "OSM",
};

const { pg_env, file_path, logging_level } = yargs(hideBin(process.argv))
  .strict()
  .options({
    file_path: file_path_yargs_config,
    pg_env: pg_env_yargs_config,
    logging_level: logging_level_yargs_config,
  }).argv;

const layer_name = basename(file_path).replace(/\.geojson\..*$/, "");

console.log(layer_name);

logger.level = logging_level;

function reviseTableDescriptor(table_descriptor) {
  const osm_id_column_type = table_descriptor.columnTypes.find(
    ({ col }) => col === "osm_id"
  );

  osm_id_column_type.db_type = "BIGINT";

  const other_tags_column_type = table_descriptor.columnTypes.find(
    ({ col }) => col === "other_tags"
  );

  other_tags_column_type.db_type = "JSONB";

  return table_descriptor;
}

const config = {
  file_path,
  layer_name,
  source_info,
  view_info,
  reviseTableDescriptor,
};

async function main() {
  const etl_context_id = await dama_events.spawnEtlContext(null, null, pg_env);

  logger.info(`==> etl_context_id: ${etl_context_id}`);

  await runInDamaContext(
    {
      meta: { pgEnv: pg_env, etl_context_id },
    },
    () => etl(config)
  );
}

main();
