#!/bin/bash

DAMA_ENV=$1

./node_modules/.bin/ts-node \
  --transpileOnly \
  ./node_modules/moleculer/bin/moleculer-runner.js \
    --envfile $1.env \
    --hot \
    --repl \
    --config moleculer.config.ts \
    src/**/*.service.ts
