#!/usr/bin/env node

require("ts-node").register();
require("tsconfig-paths").register();

const { runETLFromCLI } = require("data_utils/gis/etl");

const layer_name = "tl_2010_36_tract10";

const source_info = {
  name: "us_census_tract",
  display_name: "US Census Track",
};

const view_info = {
  table_schema: "us_census_tiger",
  table_name: "tract_2010",
  geography_version: 36,
  source_url:
    "https://www2.census.gov/geo/pvs/tiger2010st/36_New_York/36/tl_2010_36_tract10.zip",
  publisher: "US Census TIGER",
};

runETLFromCLI({
  layer_name,
  source_info,
  view_info,
  preserve_text_fields: true,
});
