#!/usr/bin/env node

require("ts-node").register();
require("tsconfig-paths").register();

const { runETLFromCLI } = require("data_utils/gis/etl");

const layer_name = "Census_Tract";

const source_info = {
  name: "us_census_tract",
  display_name: "US Census Track",
};

const view_info = {
  table_schema: "us_census_tiger",
  table_name: "tract",
  geography_version: 36,
  source_url:
    "https://www.census.gov/geographies/mapping-files/time-series/geo/tiger-geodatabase-file.2022.html",
  publisher: "US Census TIGER",
};

runETLFromCLI({
  layer_name,
  source_info,
  view_info,
  preserve_text_fields: true,
});
