#!/usr/bin/env node

require("ts-node").register();
require("tsconfig-paths").register();

const { runETLFromCLI } = require("data_utils/gis/etl");

const layer_name = "Incorporated_Place";

const source_info = {
  name: "us_incorporated_place",
  display_name: "US Incorporated Place",
  description:
    "Incorporated places are legally incorporated under state law, have a legally defined boundary, and an active functioning governmental structure. Examples of incorporated places include cities, towns, villages, etc.",
};

const view_info = {
  table_schema: "us_census_tiger",
  table_name: "incorporated_place",
  geography_version: 36,
  source_url:
    "https://www.census.gov/geographies/mapping-files/time-series/geo/tiger-geodatabase-file.2022.html",
  publisher: "US Census TIGER",
};

runETLFromCLI({
  layer_name,
  source_info,
  view_info,
  preserve_text_fields: true,
});
