#!/usr/bin/env node

require("ts-node").register();
require("tsconfig-paths").register();

const { basename } = require("path");

const dedent = require("dedent");

const { getCliArgs, runETLFromCLI } = require("data_utils/gis/etl");

const args = getCliArgs();

console.log(JSON.stringify(args, null, 4));

const { file_path } = args;

const layer_name = "geo_export_c4a2460f-ef72-40ca-a599-97eda1af243e";

const source_info = {
  name: "nyc_open_data_building_footprints",
  display_name: "NYC Open Data Building Footprints",
};

const view_info = {
  table_schema: "nyc_open_data_building_footprints",
  table_name: "buildings",
  geography_version: 36,
  publisher: "NYC Open Data",
};

runETLFromCLI({
  layer_name,
  source_info,
  view_info,
  preserve_text_fields: true,
});
