#!/bin/bash -l


set -e

pushd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null

mkdir -p logs

/usr/local/n/versions/node/14.19.1/bin/node \
  ./run transcom_events_aggregate_nightly_update \
  --pg_env production \
&> logs/nightly_etl.$(date +%s)

popd >/dev/null
