#!/usr/bin/env node

require("ts-node").register();
require("tsconfig-paths").register();

const { runETLFromCLI } = require("data_utils/gis/etl");

const layer_name = "County_Subdivision";

const source_info = {
  name: "us_county_subdivision",
  display_name: "US County Subdivision",
  description:
    "County Subdivisions fall within counties. Since each state organizes its governments differently, there are some states where the county subdivisions are established legal entities known as Minor Civil Divisions (MCDs). In the rest of the states, county subdivisions are known as Census County Divisions (CCDs) and exist for statistical purposes.",
};

const view_info = {
  table_schema: "us_census_tiger",
  table_name: "county_subdivision",
  geography_version: 36,
  source_url:
    "https://www.census.gov/geographies/mapping-files/time-series/geo/tiger-geodatabase-file.2022.html",
  publisher: "US Census TIGER",
};

runETLFromCLI({
  layer_name,
  source_info,
  view_info,
  preserve_text_fields: true,
});
