BEGIN ;

CREATE SCHEMA IF NOT EXISTS :OUTPUT_SCHEMA ;

DROP TABLE IF EXISTS :OUTPUT_SCHEMA.lcgu_output CASCADE ;

CREATE TABLE IF NOT EXISTS :OUTPUT_SCHEMA.lcgu_output (
  LIKE :LCGU_TABLE_SCHEMA.:LCGU_TABLE_NAME INCLUDING ALL
) WITH (fillfactor = 100) ;

INSERT INTO :OUTPUT_SCHEMA.lcgu_output
  SELECT
      *
    FROM :LCGU_TABLE_SCHEMA.:LCGU_TABLE_NAME
;

COMMIT ;

