#!/usr/bin/env node

require("ts-node").register();
require("tsconfig-paths").register();

const { runETLFromCLI } = require("data_utils/gis/etl");

const layer_name = "Block20";

const source_info = {
  name: "us_census_block",
  display_name: "US Census Block",
  description:
    "Census Blocks are the smallest geographic unit for which the Census Bureau collects data. Blocks represent streets, roads, and railroads, bodies of water, and other visible physical and cultural features. Census blocks are numbered uniquely with a four-digit census block number from 0000 to 9999 within census tract which nest within state and county. Census blocks are not delineated based on population.",
};

const view_info = {
  table_schema: "us_census_tiger",
  table_name: "block",
  geography_version: 36,
  source_url:
    "https://www.census.gov/geographies/mapping-files/time-series/geo/tiger-geodatabase-file.2022.html",
  publisher: "US Census TIGER",
};

runETLFromCLI({
  layer_name,
  source_info,
  view_info,
  preserve_text_fields: true,
});
