#!/bin/bash

set -e

ogr2ogr \
  -F 'ESRI Shapefile' \
  albany_county_bridges_and_culverts \
  PG:"host='127.0.0.1' user='dama_dev_user' dbname='dama_dev_1' password='3eee6405-48e5-4a1e-a6b8-82bfc80b5f17' port='5466'" \
  -sql "
    SELECT
        bin,
        wkb_geometry
      FROM nysdot_structures.bridges
      WHERE ( county = 'ALBANY' )
  " \
  -nln 'nysdot_structures_bridges' \
  -a_srs EPSG:4326
